# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

fastlane_version "2.23.0"

default_platform :ios

platform :ios do
  before_all do
    # ...
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(scheme: "SansFonts")
    deliver(force: true)
    pilot(changelog: "• Improve usability by excluding more icon fonts from being blocked.")
  end

  after_all do |lane|
    # ...
  end

  error do |lane, exception|
    # ...
  end
end

# TODO - add :mac platform
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
